# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d9043c84c3436f5d493106f1335e139072fb235f61660e5f1ec75403110a21fb807a7d7ea6760326267d4b0f0de1e859d7df1364146e99918747a39f42ee1fe

test:
  secret_key_base: f2cf2bc793fb78d61fb1edcc12017d68e13d70672e61a058324ed1d5b43081359f32f04ce4c2b90d60804c3b67d5573ee06351ebd6b56ce6feb5da20338ff79e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
